name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # On s'assure que c'est bien main ici
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Security Check
        run: |
          gem install bundler-audit
          bundle-audit update
          bundle-audit check

  deploy-test:
    needs: security-audit
    # CHANGEMENT ICI : refs/heads/main au lieu de master
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      public_changes: ${{ steps.filter.outputs.public_only }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            public_only:
              - 'public/**'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run Deployment Script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh

  create-tag:
    needs: deploy-test
    # CHANGEMENT ICI : refs/heads/main
    if: github.ref == 'refs/heads/main' && needs.deploy-test.outputs.public_changes == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.tag_step.outputs.NEW_TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create and Push Tag
        id: tag_step
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r major minor patch <<< "$VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_TAG="v$major.$minor.$NEW_PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

  notify-clients:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Mise à jour Mac-Monitor : ${{ needs.create-tag.outputs.new_tag }}"
          to: luka.salvo23@gmail.com
          from: "GitHub Actions <noreply@github.com>"
          body: |
            Hello Luka,
            Version ${{ needs.create-tag.outputs.new_tag }} créée suite à une modif dans /public.